#!/bin/bash

# Point this at a server with CUDA devices.
# Usage: $ ./run [my-server] build main
# Usage: $ ./run [my-server] test main

set -e

rl=0

if ! type perl > /dev/null 2>& 1; then
  if uname | grep -i 'darwin' > /dev/null; then
    echo 'Build requires perl on OSX.' >& 2
    exit 1
  fi
  rl=1
fi

if test $rl -eq 1; then
  file=$(readlink -f "$0")
else
  file=$(perl -MCwd -e "print Cwd::realpath('$0')")
fi

dir=$(dirname "$file")

cd ${dir}/..

SERVER=$1
ACTION=$2
NETWORK=$3

if test -z "$SERVER"; then
  echo 'Must pass an SSH server.' 2>& 1
  exit 1
fi

if test -z "$ACTION"; then
  echo 'Must pass an action.' 2>& 1
  exit 1
fi

if test -z "$NETWORK"; then
  echo 'Must pass a network.' 2>& 1
  exit 1
fi

set -ex

rm -rf cuckoo

ssh $SERVER 'rm -rf ~/hs-miner'
scp -q -r . $SERVER:~/hs-miner

ssh $SERVER "~/hs-miner/scripts/rebuild ${NETWORK}"

if test "$ACTION" = 'build'; then
  exit 0
fi

if test "$ACTION" != 'test'; then
  echo 'Must pass a valid action (build or test).' 2>& 1
  exit 1
fi

if test "$NETWORK" = 'main'; then
  # ssh $SERVER 'time node ~/hs-miner/test/stop-test.js lean'
  # ssh $SERVER 'time node ~/hs-miner/test/stop-test.js mean'
  # ssh $SERVER 'time node ~/hs-miner/test/stop-test.js lean-cuda'
  # ssh $SERVER 'time node ~/hs-miner/test/stop-test.js mean-cuda'

  # ssh $SERVER 'time node ~/hs-miner/bin/hs-mine -a -m 545259519 -b mean'
  ssh $SERVER 'time node ~/hs-miner/bin/hs-mine -a -m 545259519 -b mean-cuda'

  exit 0
fi

if test "$NETWORK" = 'simnet'; then
  # ssh $SERVER 'time node ~/hs-miner/test/stop-test.js simple'
  # ssh $SERVER 'time node ~/hs-miner/test/stop-test.js lean'
  # ssh $SERVER 'time node ~/hs-miner/test/stop-test.js lean-cuda'

  ssh $SERVER 'time node ~/hs-miner/bin/hs-mine -a -m 545259519 -b simple'
  ssh $SERVER 'time node ~/hs-miner/bin/hs-mine -a -m 545259519 -b lean'
  ssh $SERVER 'time node ~/hs-miner/bin/hs-mine -a -m 545259519 -b lean-cuda'

  exit 0
fi

echo 'Must pass a valid network.' 2>& 1
exit 1
