#!/bin/bash

set -e

rl=0

if ! type perl > /dev/null 2>& 1; then
  if uname | grep -i 'darwin' > /dev/null; then
    echo 'Build requires perl on OSX.' >& 2
    exit 1
  fi
  rl=1
fi

if test $rl -eq 1; then
  file=$(readlink -f "$0")
else
  # Have to do it this way
  # because OSX isn't a real OS
  file=$(perl -MCwd -e "print Cwd::realpath('$0')")
fi

dir=$(dirname "$file")

cd ${dir}/..

set -ex

CXX=$(test -z "$CXX" && echo 'g++' || echo "$CXX")
ENDIAN=$(bash scripts/get endian)
CUDA_HAS=$(bash scripts/get cuda_has)
NVCC=$(bash scripts/get nvcc)
NETWORK=$(bash scripts/get network)
DENDIAN=$(test "$ENDIAN" = "little" \
  && echo -DHS_LITTLE_ENDIAN \
  || echo -DHS_BIG_ENDIAN)

compile_cuda() {
  local miner="$1"

  ${NVCC} -ccbin ${CXX} --compiler-options='-fPIC' \
    $DENDIAN -DHS_HAS_CUDA -DHS_NETWORK=$NETWORK \
    -m64 -arch=sm_35 -dc -o ${miner}.o -c \
    ${miner}.cu

  ${NVCC} -ccbin ${CXX} --compiler-options='-fPIC' \
    $DENDIAN -DHS_HAS_CUDA -DHS_NETWORK=$NETWORK \
    -m64 -arch=sm_35 -dlink -o ${miner}.dlink.o \
    ${miner}.o

  ${NVCC} -ccbin ${CXX} --compiler-options='-fPIC' \
    $DENDIAN -DHS_HAS_CUDA -DHS_NETWORK=$NETWORK \
    -m64 -arch=sm_35 -lib -o ${miner}.a \
    ${miner}.o ${miner}.dlink.o
}

preprocess_cuda() {
  local miner="$1"

  ${NVCC} -E -ccbin ${CXX} --compiler-options='-fPIC' \
    $DENDIAN -DHS_HAS_CUDA -DHS_NETWORK=$NETWORK \
    -m64 -arch=sm_35 -dc -o ${miner}.cup -c \
    ${miner}.cu
}

if test -n "$EXTRA_ARG"; then
  echo "Extra: $EXTRA_ARG"
fi

echo $CUDA_HAS
if test $CUDA_HAS -eq 1; then
  compile_cuda src/device
  compile_cuda src/cuda

  if test "$EXTRA_ARG" = "preprocess"; then
    preprocess_cuda src/device
    preprocess_cuda src/cuda
  fi
else
  rm -f src/device.a
  rm -f src/cuda.a

  rm -f src/device.o
  rm -f src/cuda.o

  rm -f src/cuda/device.dlink.o
  rm -f src/cuda/cuda.dlink.o
fi

node-gyp rebuild
