#!/bin/bash

set -e

rl=0

if ! type perl > /dev/null 2>& 1; then
  if uname | grep -i 'darwin' > /dev/null; then
    echo 'Build requires perl on OSX.' >& 2
    exit 1
  fi
  rl=1
fi

if test $rl -eq 1; then
  file=$(readlink -f "$0")
else
  # Have to do it this way
  # because OSX isn't a real OS
  file=$(perl -MCwd -e "print Cwd::realpath('$0')")
fi

dir=$(dirname "$file")

cd ${dir}/..

set -ex

rm -f src/device.a
rm -f src/blake2b.a
rm -f src/sha3.a

rm -f src/device.o
rm -f src/blake2b.o
rm -f src/sha3.o

rm -f src/cuda/device.dlink.o
rm -f src/cuda/blake2b.dlink.o
rm -f src/cuda/sha3.dlink.o

node-gyp clean
