#!/bin/bash

NETWORK=$(test -n "$HS_NETWORK" && echo "$HS_NETWORK" || echo 'testnet')
OCL_PREFIX=/usr/include/CL
OS=linux
SO=so

if uname | grep -i 'darwin' > /dev/null; then
  OCL_PREFIX=/System/Library/Frameworks/OpenCL.framework/Headers
  OS=mac
  SO=dylib
fi

OCL_HEADER="$OCL_PREFIX/cl.h"

if test -n "$2"; then
  NETWORK=$2
fi

if test -z "$CUDA_PREFIX"; then
  if test -d /usr/local/cuda; then
    CUDA_PREFIX=/usr/local/cuda
  else
    CUDA_PREFIX=/opt/cuda
  fi
fi

if test -z "$CUDA_LIB"; then
  if test -d "${CUDA_PREFIX}/lib64"; then
    CUDA_LIB="${CUDA_PREFIX}/lib64"
  else
    CUDA_LIB="${CUDA_PREFIX}/lib"
  fi
fi

if test -z "$CUDA_BIN"; then
  CUDA_BIN="${CUDA_PREFIX}/bin"
fi

if test -z "$NVCC"; then
  NVCC="${CUDA_BIN}/nvcc"
fi

case "$1" in
  cuda)
    echo "$CUDA_PREFIX"
  ;;
  cuda_lib)
    echo "$CUDA_LIB"
  ;;
  cuda_bin)
    echo "$CUDA_BIN"
  ;;
  cuda_has)
    if test ! -d "$CUDA_BIN" \
      || test ! -d "$CUDA_LIB" \
      || test ! -x "${NVCC}" \
      || test ! -e "${CUDA_LIB}/libcudart.${SO}"; then
      echo 0
    else
      echo 1
    fi
  ;;
  nvcc)
    echo "$NVCC"
  ;;
  os)
    echo "$OS"
  ;;
  ocl_has)
    if test ! -f "$OCL_HEADER"; then
      echo 0
    else
      echo 1
    fi
  ;;
  endian)
    python -c \
      'from __future__ import print_function; import sys; print(sys.byteorder)'
  ;;
  network)
    case "$NETWORK" in
      main | testnet | regtest | simnet)
      ;;
      *)
        echo 'Bad network.' 2>& 1
        exit 1
      ;;
    esac
    echo "$NETWORK"
  ;;
  *)
    echo 'Bad action.' 2>& 1
    exit 1
  ;;
esac
